### ISSUE TITLE
Mastodon support

### ISSUE THREAD

**Issue by watzon** [webistomin/vue-socials#569]
Seeing as so many people are frequenting mastodon now it would be really nice to have a mastodon button as well. I've yet to see a single library add support since a mastodon share button would require a modal or something to enter your instance address, which tends to upset the simple "click and go" flow.

**Comment by webistomin** [comment]
Hey! I'll take a look at the issue soon. I think the interface should look like this:

```ts
interface IMastodonShareOptions {
  domain?: string
  text?: string;
  url?: string;
}
```

 Leave the modal window to users, as the design may not be suitable.

**Comment by watzon** [comment]
Seems great :) would love to see this get added for sure. Thanks for the quick response.

**Comment by webistomin** [comment]
Available in `v2.0.0` for `vue 3`

```vue
<template>
  <s-mastodon
    :window-features="windowFeatures"
    :share-options="shareOptions"
    :use-native-behavior="useNativeBehavior"
    @popup-close="onClose"
    @popup-open="onOpen"
    @popup-block="onBlock"
    @popup-focus="onFocus"
  ></s-mastodon>
</template>

<script>
  import { SMastodon } from 'vue-socials'

  export default {
    name: 'SSMastodonSharing',
    
    components: { SMastodon },
    
    data() {
      return {
        windowFeatures: {},
        shareOptions: {
          domain: 'https://mas.to',
          url: 'https://github.com',
          text: 'Hello, world!',
        },
        useNativeBehavior: false,
      }
    },
    
    methods: {
      onClose() {},
      onOpen() {},
      onBlock() {},
      onFocus() {},
    }
  };
</script>
```

**Comment by watzon** [comment]
My dude. Absolute legend. Thanks!

**Comment by watzon** [comment]
How would you recommend allowing the user to provide a domain before launching the window? I'd like to have it so that clicking the button launches a modal that asks for the mastodon domain, and then clicking Ok on the modal triggers the click event on the vue-social button, passing in the user's provided domain.

**Comment by watzon** [comment]
Ahhhh smart. Thanks again!
