### ISSUE TITLE
SMastodon broken in 2.0.1?

### ISSUE THREAD

**Issue by Sjoerd82** [webistomin/vue-socials#585]
Something is up with the SMastodon component in v2.0.1.

It can only be imported like so:
```ts
    import {
        SWhatsApp,
        STelegram,
        SEmail,
        SFacebook,
        STwitter,
        SReddit,
        SPinterest,
        SPocket,
    } from 'vue-socials'
    import SMastodon from 'vue-socials'
```

And when imported this way, it's not working, and it is not supporting the standard properties like shareOptions, etc.

**Comment by webistomin** [comment]
Fixed in `v2.0.2`
